#!/bin/bash

# shell script to set watches on directory
# @param $1 — the the file or directory to set watch on

# load default configuration
source /etc/forkforge.conf
# load user-specific config
if [ -f $HOME_DIR/.forkforgerc ] ; then
  source $HOME_DIR/.forkforgerc
fi

ICFILE=$INCRON_DIR/$FF_NAME⇑
ICFILE_REMOTE=$INCRON_DIR/$FF_NAME⇓
# to add a string to 
#ICFILE_CONTENT=( "${ICFILE_CONTENT[@]}" "new element" )
#ICFILE_CONTENT[${#ICFILE_CONTENT[*]}]="new element"

if [ x$1 != x ]; then
  # store a full path for future use
  FULLPATH=$(readlink -e -s -n $1)
  if [ x$FULLPATH != x ] ; then
    CURR=$FULLPATH
    if [ -f $CURR ] ; then
      # let's check if this file is already watched
      grep -e "^$CURR " $ICFILE 2>&1 > /dev/null && exit 111
      CURR=$(dirname $CURR)
    fi
    if [ -d $CURR ] ; then
      while [ x$CURR != x$ROOT_DIR ] ; do
        # let's check if this directory is already watched
        grep -e "^$CURR " $ICFILE 2>&1 > /dev/null && exit 112
        CURR=$(readlink -e -s -n $CURR/..)
      done
      echo \
$FULLPATH IN_NO_LOOP,IN_CREATE,IN_MODIFY,IN_MOVED_TO \
          IN_DELETE,IN_MOVED_FROM \
          IN_DELETE_SELF,IN_MOVE_SELF \
      ff_synch_up \$@/\$# \$% \
      >> $ICFILE
      echo \
`ff_get_remote_dir $FULLPATH` IN_NO_LOOP,IN_CREATE,IN_MODIFY,IN_MOVED_TO \
          IN_DELETE,IN_MOVED_FROM \
          IN_DELETE_SELF,IN_MOVE_SELF \
      ff_synch_dn \$@/\$# \$% \
      >> $ICFILE_REMOTE
    fi
  else
    exit 110
  fi
else
  exit 103
fi
