#!/bin/bash

# load default configuration
source /etc/forkforge.conf
# load user-specific config
if [ -f $HOME_DIR/.forkforgerc ] ; then
  source $HOME_DIR/.forkforgerc
fi

# log the message/error 
function ff_log { 
  if [ x"$LOG_LEVEL" == x"ALL" ]; then 
    logger -f $LOG_FILE -s "[$FF_NAME] [LOG] $1"; 
  fi
}
function ff_info {
  logger -f $LOG_FILE "[$FF_NAME] [INF] $1"
}
function ff_err {
  logger -f $LOG_FILE "[$FF_NAME] [ERR] $1"
}

# mount/unmount remote filesystem
function ff_ssh_mount {
  sshfs $REMOTE_HOST_USER@$REMOTE_HOST:$REMOTE_HOST_DIR $REMOTE_DIR 2>/dev/null
}
function ff_ssh_umount {
  fusermount -u $REMOTE_DIR
}
function ff_is_mounted {
  mount | grep $REMOTE_HOST_DIR
}

# init reconnections of remote
function ff_install {
  cat << EOF > $IFACE_UP_DIR/$QUEUE-$FF_NAME
[ "$IFACE" != "lo" ] || exit 0
sshfs $REMOTE_HOST_USER@$REMOTE_HOST:$REMOTE_HOST_DIR $REMOTE_DIR 2>/dev/null && \
ff_total_sync && \
service incron start
EOF
  cat << EOF > $IFACE_DOWN_DIR/$QUEUE-$FF_NAME
[ "$IFACE" != "lo" ] || exit 0
service incron stop && fusermount -u $REMOTE_DIR
EOF
  mkdir -p $IFACE_UP_DIR_SURROGATE && \
    pushd $IFACE_UP_DIR_SURROGATE && \
    ln -s $IFACE_UP_DIR/$QUEUE-$FF_NAME && \
    popd
}
function ff_uninstall {
  rm -rf $IFACE_UP_DIR/$QUEUE-$FF_NAME
  rm -rf $IFACE_DOWN_DIR/$QUEUE-$FF_NAME
  rm -rf $IFACE_UP_DIR_SURROGATE/$QUEUE-$FF_NAME
}
