#!/bin/bash

# load default configuration
source /etc/forkforge.conf
# load user-specific config
source $HOME_DIR/.forkforgerc

# log the message/error 
ff_log() { 
  if [ x"$LOG_LEVEL" == x"ALL" ]; then 
    logger -f $LOG_FILE -s "[LOG] $1"; 
  fi
}
ff_info() {
  logger -f $LOG_FILE "[INFO] $1"
}
ff_err() {
  logger -f $LOG_FILE "[ERR] $1"
}

# mount/unmount remote filesystem
ff_mount() {
  sshfs $REMOTE_USR@$REMOTE_HST:$REMOTE_DIR $SSHFS_DIR 2>/dev/null
}
ff_umount() {
  fusermount -u $SSHFS_DIR
}

# init reconnections of remote
ff_install() {
  cat << EOF > $INITSSHFS_UP_DIR/$QUEUE-$FF_NAME
sshfs $REMOTE_USR@$REMOTE_HST:$REMOTE_DIR $SSHFS_DIR 2>/dev/null && service incron start
EOF
  cat << EOF > $INITSSHFS_DOWN_DIR/$QUEUE-$FF_NAME
service incron stop && fusermount -u $SSHFS_DIR
EOF
  mkdir -p $INITSSHFS_UP_DIR_SURROGATE && \
    pushd $INITSSHFS_UP_DIR_SURROGATE && \
    ln -s $INITSSHFS_UP_DIR/$QUEUE-$FF_NAME && \
    popd
}
ff_uninstall() {
  rm -rf $INITSSHFS_UP_DIR/$QUEUE-$FF_NAME
  rm -rf $INITSSHFS_DOWN_DIR/$QUEUE-$FF_NAME
  rm -rf $INITSSHFS_UP_DIR_SURROGATE/$QUEUE-$FF_NAME
}
