#!/bin/bash

# returns the sshfs directory mirroring the directory given as argument

# load default configuration
source /etc/forkforge.conf

# produces platform-independent name for directory
# e. g. /home/am/Work goes ⌂/Work
if [ x"$1" != x ]; then
  echo $1 | sed -e "s#$HOME_DIR#/⌂#" -e 's#/#⇒#g'
else 
  exit 102
fi
