#!/bin/bash

# returns the local directory mirroring the sshfs directory given as argument

# load default configuration
source /etc/forkforge.conf
# load user-specific config
if [ -f $HOME_DIR/.forkforgerc ] ; then
  source $HOME_DIR/.forkforgerc
fi

# produces platform-independent name for directory
# e. g. /var/forkforge/⌂/Work goes /home/am/Work
if [ x$1 != x ]; then
  echo $1 | sed -e "s#$SSHFS_DIR##" -e "s#/⌂#$HOME_DIR#"
else 
  exit 102
fi
