#!/bin/bash

# shell script to remove watch from incron file given as argument
# * actually all that stuff may be easyly done using
# * sed -e '#$CURR#/d' and if [ $(wc -l $ICFILE) -gt $(wc -l $ICFILE_NEW) ]
# * but this way is about 20% quicker

# @param $1 — the file or directory to remove incron watch from

# load default configuration
source /etc/forkforge.conf
source /usr/bin/ff_functions
# load user-specific config
if [ -f $HOME_DIR/.forkforgerc ] ; then
  source $HOME_DIR/.forkforgerc
fi

if [ x$1 == x ]; then
  exit 104 # bad input
fi

# get the full path (/home/am/blah/foo/bah/zee.zo)
CURR=$(readlink -e -s -n $1)
if [ x$CURR == x ] ; then 
  exit 106; # file given is not really a file
fi

for LOCREM in $CURR $(ff_get_remote_dir $CURR) ; do
  ICFILE=$INCRON_DIR/$FF_NAME
  ff_log "ICFILE: $ICFILE"
  if [ $LOCREM == $CURR ] ; then
   ICFILE=$ICFILE⇑
  else
   ICFILE=$ICFILE⇓
  fi
  ff_log "ICFILE: $ICFILE"
  
  # create an array of incron file entries
  declare -a ICFILE_CONTENT
  IFS=$'\n' ICFILE_CONTENT=( $(< $ICFILE) )

  # create an array filtered by $LOCREM
  #   those lines, matched $LOCREM* FIXME am I right here?
  declare -a ICFILE_RESULT=( ${ICFILE_CONTENT[@]##$LOCREM*} )
  if [ ${#ICFILE_CONTENT[@]} -gt ${#ICFILE_RESULT[@]} ] ; then
    # we found matching line, let's drop
    rm -rf $ICFILE
    for i in ${ICFILE_RESULT[@]}; do
      echo $i >> $ICFILE
    done
  fi
done
