#!/bin/bash

# shell script to remove watches on directory
# @param $1 — the the file or directory to set watch on

# load default configuration
source /etc/forkforge.conf
# load user-specific config
if [ -f $HOME_DIR/.forkforgerc ] ; then
  source $HOME_DIR/.forkforgerc
fi

# get the full path (/home/am/blah/foo/bah/zee.zo)
# FIXME removal of incron entry must be moved to ff_synch_up
W_LOCAL=$(readlink -e -s -n $1)
W_REMOTE=$(ff_get_remote_dir $W_LOCAL)
ff_synch_dn $W_REMOTE 'IN_DELETE'
