#!/bin/bash

# shell script to upload watched items
# @param $1 — the file to be uploaded (fully qualified)
# @param $2 — an action to be done on file

# load default configuration
source /etc/forkforge.conf
# load user-specific config
if [ -f $HOME_DIR/.forkforgerc ] ; then
  source $HOME_DIR/.forkforgerc
fi

# get the full path (/home/am/blah/foo/bah/zee.zo)
W_REMOTE=$(readlink -e -s -n $1)
shift
if [ x$1 == x -o x$W_REMOTE == x ] ; then 
  # shit happens
  exit 202
fi

W_LOCAL=$(ff_get_local_dir $W_REMOTE)

case $1 in
  IN_CREATE|IN_MOVED_TO)
    if [ -f $W_REMOTE ] ; then
      mkdir -p $(dirname $W_LOCAL)
      if ! ff_compare $W_LOCAL ; then
        ff_rem_incron_entry $W_LOCAL
        ff_decrypt $W_REMOTE > $W_LOCAL
        ff_add_incron_entry $W_LOCAL
      fi
    else
      mkdir -p $W_LOCAL
    fi
  ;; 
  IN_MODIFY)
    # FIXME PREVENT LOOP HERE !!!
    if ! ff_compare $W_LOCAL ; then
      mkdir -p $(dirname $W_LOCAL)
      if [ -f $W_REMOTE ] ; then
        ff_rem_incron_entry $W_LOCAL
        ff_decrypt $W_REMOTE > $W_LOCAL
        ff_add_incron_entry $W_LOCAL
      fi
    else
      mkdir -p $W_LOCAL
    fi
  ;;
  IN_DELETE|IN_MOVED_FROM)
    # FIXME PREVENT LOOP HERE !!!
    rm -rf $W_LOCAL
  ;;
  IN_DELETE_SELF|IN_MOVE_SELF)
    ff_rem_incron_entry $W_LOCAL
    rm -rf $W_LOCAL
  ;;
  *)
    exit 104
  ;;
esac
