#!/bin/bash

# shell script to upload watched items
# @param $1 — the file to be uploaded (fully qualified)
# @param $2 — an action to be done on file

# load default configuration
source /etc/forkforge.conf
source /usr/bin/ff_functions
# load user-specific config
if [ -f $HOME_DIR/.forkforgerc ] ; then
  source $HOME_DIR/.forkforgerc
fi

#IS_ONLINE=$(mount | grep $REMOTE_DIR)
#IS_OL=$?
IS_OL=0

# get the full path (/home/am/blah/foo/bah/zee.zo)
W_LOCAL=$(readlink -e -s -n $1)
shift
if [ x$1 == x -o x$W_LOCAL == x ] ; then 
  # shit happens
  exit 201
fi

W_REMOTE=$(ff_get_remote_dir $W_LOCAL)

case $1 in
  IN_CREATE|IN_MOVED_TO|IN_MODIFY)
    if [ $IS_OL -eq 0 ] ; then
      if [ -f $W_LOCAL ] ; then
        ff_log "Is file"
        mkdir -p $(dirname $W_REMOTE)
        ff_log "Made $(dirname $W_REMOTE)"
        ff_compare $W_LOCAL
        if [ $? -gt 0 ] ; then
          ff_log "Not compared"
          ff_rem_incron_entry $W_LOCAL
          ff_log "Removed incron entry"
          ff_encrypt $W_LOCAL > $W_REMOTE 
          ff_log "Encrypted"
          ff_add_incron_entry $W_LOCAL
          ff_log "Added incron entry"
        fi
      else
        mkdir -p $W_REMOTE
      fi
    fi
  ;; 
  IN_DELETE|IN_MOVED_FROM)
    # FIXME PREVENT LOOP HERE !!!
    if [ $IS_OL -eq 0 ] ; then
      rm -rf $W_REMOTE
    fi
  ;;
  IN_DELETE_SELF|IN_MOVE_SELF)
    ff_rem_incron_entry $W_LOCAL
    if [ $IS_OL -eq 0 ] ; then
      rm -rf $W_REMOTE
    fi
  ;;
  *)
    exit 103
  ;;
esac
