#!/bin/bash

# shell script to set watches on directory
# @param $1 — the the file or directory to set watch on

# load default configuration
source /etc/forkforge.conf

ICFILE=$INCRON_DIR/$FF_NAME⇑
ICFILE=/tmp/olala
# to add a string to 
#ICFILE_CONTENT=( "${ICFILE_CONTENT[@]}" "new element" )
#ICFILE_CONTENT[${#ICFILE_CONTENT[*]}]="new element"

if [ -n $1 ]; then
  FULLPATH=`readlink -e -s -n $1`
  CURR=$FULLPATH
  if [ x$FULLPATH != x ] ; then
    if [ -f $CURR ] ; then
      grep -e "^$CURR " $ICFILE 2>&1 > /dev/null && exit 111
      CURR=`dirname $CURR`
    fi
    if [ -d $CURR ] ; then
      while [ x$CURR != x$ROOT_DIR ] ; do
        grep -e "^$CURR " $ICFILE 2>&1 > /dev/null && exit 112
        CURR=`readlink -e -s -n $CURR/..`
      done     
      echo \
$FULLPATH IN_NO_LOOP,IN_CREATE,IN_MODIFY,IN_MOVED_TO \
          IN_DELETE,IN_MOVED_FROM \
          IN_DELETE_SELF,IN_MOVE_SELF \
    ff_upload \$@ \$# \$% \
    >> $ICFILE
    fi
  else
    exit 110
  fi
else
  exit 103
fi
